[package]
name = "xbounded"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
postcard = { version = "1.0.8", features = ["experimental-derive"], optional = true }
